[app]
video_source = "pexels"
pexels_api_keys = [ "xHzIFxvXdLjrEfU5cJF2r80KtliD7lL1W0bquo3lqUKFyYwIAyvaiQMt",]
pixabay_api_keys = []
llm_provider = "gemini"
ollama_base_url = ""
ollama_model_name = ""
openai_api_key = ""
openai_base_url = ""
openai_model_name = "gpt-4-turbo"
moonshot_api_key = ""
moonshot_base_url = "https://api.moonshot.cn/v1"
moonshot_model_name = "moonshot-v1-8k"
oneapi_api_key = ""
oneapi_base_url = ""
oneapi_model_name = ""
g4f_model_name = "gpt-3.5-turbo"
azure_api_key = ""
azure_base_url = ""
azure_model_name = "gpt-35-turbo"
azure_api_version = "2024-02-15-preview"
gemini_api_key = "AIzaSyCFgaPiDbbAlT_FHaVDEkVMA2kjORZG5q4"
gemini_model_name = "gemini-1.5-flash"
qwen_api_key = ""
qwen_model_name = "qwen-max"
deepseek_api_key = ""
deepseek_base_url = "https://api.deepseek.com"
deepseek_model_name = "deepseek-chat"
subtitle_provider = "edge"
endpoint = ""
material_directory = ""
enable_redis = false
redis_host = "localhost"
redis_port = 6379
redis_db = 0
redis_password = ""
max_concurrent_tasks = 5
hide_config = false
ffmpeg_ram_limit = 7.0
max_ffmpeg_processes = 3
ffmpeg_threads_per_process = 2
tts_provider = "openai fm"
openai_fm_tone = "Calm, encouraging, and articulate"

[whisper]
model_size = "large-v3"
device = "CPU"
compute_type = "int8"

[proxy]

[azure]
speech_key = ""
speech_region = ""

[ui]
language = "vi"
hide_log = false
voice_name = "openai_fm-onyx-Unisex"
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "#FFFFFF"
font_size = 59

[google_drive]
credentials_file = "credentials.json"
token_file = "token.json"
